/**
 * electron-builder configuration
 * Produces installers for Windows (NSIS), macOS (DMG), and Linux (AppImage + deb)
 */

const { version } = require('./package.json');

module.exports = {
  appId:       'com.aritamaguchi.desktop',
  productName: 'Aritamaguchi',
  copyright:   `Copyright © ${new Date().getFullYear()} Aritamaguchi`,

  // Source files to include in the app package
  files: [
    '**/*',
    '!scripts/**',
    '!.git*',
  ],

  // App icon (must exist before build; generated by `npm run icons`)
  icon: 'assets/icon',

  // Extra resources bundled into the installed app
  extraResources: [
    { from: 'assets/', to: 'assets/', filter: ['*.png', '*.ico', '*.icns'] },
  ],

  // ── Windows (NSIS) ──────────────────────────────────────────────────────────
  win: {
    target: [
      { target: 'nsis', arch: ['x64', 'ia32'] },
      { target: 'portable', arch: ['x64'] },
    ],
    icon: 'assets/icon.ico',
    requestedExecutionLevel: 'asInvoker',
  },

  nsis: {
    oneClick:            false,
    allowToChangeInstallationDirectory: true,
    installerIcon:       'assets/icon.ico',
    uninstallerIcon:     'assets/icon.ico',
    installerHeaderIcon: 'assets/icon.ico',
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName:        'Aritamaguchi',
    // Custom installer script lines (runs after install)
    include: null,
  },

  // ── macOS (DMG) ─────────────────────────────────────────────────────────────
  mac: {
    target: [
      { target: 'dmg',  arch: ['x64', 'arm64'] },
      { target: 'zip',  arch: ['x64', 'arm64'] },
    ],
    icon:     'assets/icon.icns',
    category: 'public.app-category.entertainment',
  },

  dmg: {
    title:       `Aritamaguchi ${version}`,
    background:  'assets/dmg-background.png',
    contents: [
      { x: 410, y: 150, type: 'link', path: '/Applications' },
      { x: 130, y: 150, type: 'file' },
    ],
    window: { width: 540, height: 380 },
  },

  // ── Linux ───────────────────────────────────────────────────────────────────
  linux: {
    target: [
      { target: 'AppImage', arch: ['x64'] },
      { target: 'deb',      arch: ['x64'] },
    ],
    icon:        'assets/icon.png',
    category:    'Game',
    description: 'Digimon desktop pet that wanders around your screen',
    maintainer:  'Aritamaguchi <hello@aritamaguchi.app>',
  },

  deb: {
    depends: ['libgtk-3-0', 'libnotify4', 'libnss3', 'libxss1', 'libxtst6', 'xdg-utils'],
  },

  // ── Build metadata ──────────────────────────────────────────────────────────
  publish: null, // disable auto-publish (set to GitHub/S3 for auto-update)
};
